FROM golang:1.22-bullseye as dev
WORKDIR /app

COPY map.proto /app
COPY ./server/go.mod .
RUN apt-get update -y -qq
RUN apt-get install -y -qq protobuf-compiler
RUN go install github.com/cosmtrek/air@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
COPY ./server .
RUN go env -w CGO_ENABLED=0
RUN ./build.dev.sh
CMD ["/go/bin/app"]